### ISSUE TITLE
Practice describing - save the users own description

### ISSUE THREAD

**Issue by sueannma** [benetech/PoetTraining#22]
- As a publisher learning to write complex image descriptions, I would like to have the option to save the image and associated description so that I may review it on my own machine at a later time.
- As an administrator of the Poet Training Tool, I would like to know how often the Practice Description section has been used and what outputs have been produced using the available features. 
[Practice Describing Mock.pdf](https://github.com/benetech/PoetTraining/files/864817/Practice.Describing.Mock.pdf)

**Comment by Rdbaker** [comment]
@sueannma can you give a user story for this? It'd help define how the functionality/UI would be impacted 

Also, for something like this, I think it'd be good to have (if we care about security) a backend server

**Comment by sueannma** [comment]
@Rdbaker - I updated this issue ticket as well as #21 as well, both with the same basic mockup attached as they are closely linked. I tried to separate this ticket out as there are a few ways to explore the secord user story. We might benefit from a lightweight backend server to start, but would be interested in better understanding the effort required in that event.

**Comment by sueannma** [comment]
closing as dup
