### ISSUE TITLE
As a describer, I would like to be presented a list of image types by group 

### ISSUE THREAD

**Issue by sueannma** [benetech/PoetTraining#28]
recommendation for presenting a dropdown with nested sub-items: https://jsfiddle.net/v3w72e3h/

o	I would like to view the image classes by grouped category, then specific image class, similar to how it’s presented in the Table of Contents at the left of the How to Describe page
o	I would like the option to assign the image class “None/Not Sure” for my uploaded image  
o	If “None/Not Sure” is selected, present the following as the guidelines: 
You did not select a specific image classification, so we do not have any best practice guidelines to share. If you would like to select an image classification to review our recommendations, please close this modal, select a specific image classification, and try again.”

**Comment by sholzer20** [comment]
This issue appears to have been addressed in the training tool. If not, can you specify what else should be fixed?
